/* Monee — cloud-sync version */
const SUPABASE_URL = "https://tdyobrprvphxycfvowpp.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_DCxp0EkCpv3s_bs5RaGymw_Xe8MMDg2";
const CLOUD_CONFIGURED = Boolean(SUPABASE_URL && SUPABASE_ANON_KEY && window.supabase);
const supabaseClient = CLOUD_CONFIGURED ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;

const defaultCategories = { expense:["Grocery Shopping","Outside Food","Fashion Shopping","Utility Bills","Car Expenses","Medical Expenses","Entertainment","Vacation Expenses","Others"], income:["Salary","Freelance","Gift","Investment","Other"] };
const symbols = {"Grocery Shopping":"🛒","Outside Food":"🍽","Fashion Shopping":"🛍","Utility Bills":"◉","Car Expenses":"🚗","Medical Expenses":"✚",Entertainment:"★","Vacation Expenses":"✈",Others:"•",Salary:"▣",Freelance:"⌘",Gift:"♡",Investment:"↗",Other:"•"};
const $ = id => document.getElementById(id);
let state = {period:"month",type:"expense",editingId:null,entries:JSON.parse(localStorage.getItem("monee-entries")||"[]"),categories:JSON.parse(localStorage.getItem("monee-categories")||"null")||JSON.parse(JSON.stringify(defaultCategories)),user:null};
const money = {format:value=>`⃁ ${Number(value).toLocaleString("en-SA",{minimumFractionDigits:2,maximumFractionDigits:2})}`};
const today = ()=>new Date().toISOString().slice(0,10);
function localPersist(){localStorage.setItem("monee-entries",JSON.stringify(state.entries));localStorage.setItem("monee-categories",JSON.stringify(state.categories));}
function setSyncStatus(text){if($("syncStatus"))$("syncStatus").textContent=text;}
function escapeHTML(s){const d=document.createElement("div");d.textContent=s;return d.innerHTML;}
function migrateDefaultExpenseCategories(){if(localStorage.getItem("monee-category-migration-v2"))return;const mapping={Food:"Grocery Shopping",Transport:"Car Expenses",Shopping:"Fashion Shopping",Bills:"Utility Bills",Health:"Medical Expenses",Other:"Others"};state.entries.forEach(e=>{if(e.type==="expense"&&mapping[e.category])e.category=mapping[e.category]});const oldDefaults=["Food","Transport","Shopping","Bills","Health","Entertainment","Other"];const custom=state.categories.expense.filter(c=>!oldDefaults.includes(c));state.categories.expense=[...defaultCategories.expense,...custom.filter(c=>!defaultCategories.expense.includes(c))];localStorage.setItem("monee-category-migration-v2","true");localPersist();}
function samePeriod(date){const d=new Date(date+"T12:00:00"),now=new Date();if(state.period==="all")return true;if(state.period==="month")return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();const start=new Date(now);start.setHours(0,0,0,0);start.setDate(now.getDate()-((now.getDay()+6)%7));return d>=start;}
function categoryOptions(){$("category").innerHTML=state.categories[state.type].map(x=>`<option>${escapeHTML(x)}</option>`).join("");renderCategoryManager();}
function renderCategoryManager(){$("editableCategories").innerHTML=state.categories[state.type].map((name,index)=>`<button class="category-chip" type="button" data-category-index="${index}"><span>${escapeHTML(name)}</span><i aria-hidden="true">✎</i></button>`).join("");document.querySelectorAll("[data-category-index]").forEach(button=>button.onclick=()=>renameCategory(Number(button.dataset.categoryIndex)));}
async function saveCategoriesCloud(){if(!state.user)return;for(const type of ["expense","income"]){const {error}=await supabaseClient.from("categories").upsert({user_id:state.user.id,type,names:state.categories[type],updated_at:new Date().toISOString()},{onConflict:"user_id,type"});if(error)throw error;}}
async function renameCategory(index){const oldName=state.categories[state.type][index],newName=prompt("Rename category",oldName);if(newName===null)return;const name=newName.trim();if(!name||name===oldName)return;if(state.categories[state.type].some(c=>c.toLowerCase()===name.toLowerCase()))return alert("That category already exists.");state.categories[state.type][index]=name;state.entries.forEach(e=>{if(e.type===state.type&&e.category===oldName)e.category=name});localPersist();categoryOptions();refreshFilters();render();try{await saveCategoriesCloud();if(state.user)await syncEntriesToCloud();setSyncStatus("Synced")}catch(e){console.error(e);setSyncStatus("Local only");alert("Saved locally, but cloud sync failed: "+e.message);}}
function getEntries(){const type=$("typeFilter").value,cat=$("categoryFilter").value;return state.entries.filter(e=>samePeriod(e.date)&&(type==="all"||e.type===type)&&(cat==="all"||e.category===cat));}
function refreshFilters(){const current=$("categoryFilter").value;const cats=[...new Set(state.entries.filter(e=>e.type==="expense").map(e=>e.category))];$("categoryFilter").innerHTML='<option value="all">All categories</option>'+cats.map(c=>`<option>${escapeHTML(c)}</option>`).join("");$("categoryFilter").value=cats.includes(current)?current:"all";}
function render(){refreshFilters();const entries=getEntries(),income=entries.filter(e=>e.type==="income").reduce((a,e)=>a+Number(e.amount),0),expense=entries.filter(e=>e.type==="expense").reduce((a,e)=>a+Number(e.amount),0);$("balanceValue").textContent=money.format(income-expense);$("incomeValue").textContent=money.format(income);$("expenseValue").textContent=money.format(expense);$("periodLabel").textContent=state.period==="week"?"Monday–today":state.period==="month"?new Intl.DateTimeFormat(undefined,{month:"long"}).format(new Date()):"Everything";renderChart(entries);renderCategories(entries);renderTransactions(entries);}
function renderChart(entries){const expenses=entries.filter(e=>e.type==="expense"),days=state.period==="week"?7:state.period==="month"?Math.min(new Date().getDate(),7):7,totals=Array(days).fill(0);$("chartEmpty").hidden=expenses.length>0;expenses.forEach(e=>{const d=new Date(e.date+"T12:00:00"),pos=state.period==="week"?((d.getDay()+6)%7):d.getDate()%days;totals[pos]+=Number(e.amount)});const max=Math.max(...totals,1);$("chart").innerHTML=totals.map((v,i)=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(4,v/max*100)}%" title="${money.format(v)}"></div><span>${state.period==="week"?["M","T","W","T","F","S","S"][i]:i+1}</span></div>`).join("");}
function renderCategories(entries){const grouped={};entries.filter(e=>e.type==="expense").forEach(e=>grouped[e.category]=(grouped[e.category]||0)+Number(e.amount));const rows=Object.entries(grouped).sort((a,b)=>b[1]-a[1]).slice(0,3);$("categoryList").innerHTML=rows.length?rows.map(([c,v])=>`<div class="category-row"><span class="category-dot">${symbols[c]||"•"}</span><div class="category-info"><b>${escapeHTML(c)}</b><small>${money.format(v)} spent</small></div><strong class="expense">${money.format(v)}</strong></div>`).join(""):'<p class="empty-message">Your expense categories will appear here.</p>';}
function renderTransactions(entries){const sorted=[...entries].sort((a,b)=>b.date.localeCompare(a.date));$("transactionList").innerHTML=sorted.length?sorted.map(e=>`<div class="transaction"><span class="transaction-icon">${symbols[e.category]||"•"}</span><div class="transaction-info"><b>${escapeHTML(e.description)}</b><small>${escapeHTML(e.category)} · ${new Date(e.date+"T12:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric"})}</small><div class="entry-actions"><button type="button" class="edit-entry" data-entry-id="${e.id}">Edit</button><button type="button" class="delete-entry" data-entry-id="${e.id}">Delete</button></div></div><strong class="${e.type}">${e.type==="income"?"+":"−"}${money.format(e.amount)}</strong></div>`).join(""):'<p class="empty-message">No transactions for this view.</p>';document.querySelectorAll(".edit-entry").forEach(b=>b.onclick=()=>editEntry(b.dataset.entryId));document.querySelectorAll(".delete-entry").forEach(b=>b.onclick=()=>deleteEntry(b.dataset.entryId));}
function openNewTransaction(){state.editingId=null;$("transactionForm").reset();state.type="expense";$("date").value=today();document.querySelectorAll(".type-choice").forEach(x=>x.classList.toggle("active",x.dataset.type===state.type));$("categoryManager").hidden=true;categoryOptions();$("transactionDialog").showModal();}
function editEntry(id){const entry=state.entries.find(e=>e.id===id);if(!entry)return;state.editingId=id;state.type=entry.type;if(!state.categories[entry.type].includes(entry.category))state.categories[entry.type].push(entry.category);document.querySelectorAll(".type-choice").forEach(x=>x.classList.toggle("active",x.dataset.type===state.type));categoryOptions();$("description").value=entry.description;$("amount").value=entry.amount;$("category").value=entry.category;$("date").value=entry.date;$("categoryManager").hidden=true;$("transactionDialog").showModal();}
async function deleteEntry(id){const entry=state.entries.find(e=>e.id===id);if(!entry||!confirm(`Delete “${entry.description}”?`))return;state.entries=state.entries.filter(e=>e.id!==id);localPersist();render();if(!state.user){setSyncStatus(CLOUD_CONFIGURED?"Not signed in":"Local only");return;}try{const {error}=await supabaseClient.from("entries").delete().eq("id",id).eq("user_id",state.user.id);if(error)throw error;setSyncStatus("Synced");}catch(e){console.error(e);setSyncStatus("Local only");alert("Deleted locally, but cloud sync failed: "+e.message);}}
async function saveEntryCloud(entry){if(!state.user)return;const row={id:entry.id,user_id:state.user.id,type:entry.type,description:entry.description,amount:Number(entry.amount),category:entry.category,date:entry.date};const {error}=await supabaseClient.from("entries").upsert(row,{onConflict:"id"});if(error)throw error;}
async function syncEntriesToCloud(){if(!state.user)return;for(const entry of state.entries)await saveEntryCloud(entry);}
async function loadCloudData(){if(!state.user)return;setSyncStatus("Syncing…");const [{data:cloudEntries,error:e1},{data:cloudCats,error:e2}]=await Promise.all([supabaseClient.from("entries").select("id,type,description,amount,category,date").eq("user_id",state.user.id),supabaseClient.from("categories").select("type,names").eq("user_id",state.user.id)]);if(e1)throw e1;if(e2)throw e2;const cloudIds=new Set((cloudEntries||[]).map(e=>e.id));const localOnly=state.entries.filter(e=>!cloudIds.has(e.id));if(localOnly.length)for(const e of localOnly)await saveEntryCloud(e);const merged=[...(cloudEntries||[]),...localOnly].map(e=>({...e,amount:Number(e.amount)}));state.entries=merged;const categoryRows=cloudCats||[];if(categoryRows.length){categoryRows.forEach(row=>{if(Array.isArray(row.names))state.categories[row.type]=row.names});}else{await saveCategoriesCloud();}localPersist();render();setSyncStatus("Synced");}
function showAuth(show){$("authGate").hidden=!show;$("appShell").hidden=show;$("addButton").hidden=show;}
async function signInOrSignUp(event){event.preventDefault();const email=$("authEmail").value.trim(),password=$("authPassword").value;const signup=$("authToggle").dataset.signup==="true";$("authMessage").textContent=signup?"Creating account…":"Signing in…";try{const result=signup?await supabaseClient.auth.signUp({email,password}):await supabaseClient.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(signup&&!result.data.session){$("authMessage").textContent="Account created. Check your email to confirm it, then sign in.";return;}state.user=result.data.user;showAuth(false);await loadCloudData();}catch(e){console.error(e);$("authMessage").textContent=e.message||"Authentication failed.";}}
function setupAuth(){if(!CLOUD_CONFIGURED){showAuth(false);setSyncStatus("Local only");return;}$("authForm").onsubmit=signInOrSignUp;$("authToggle").onclick=()=>{const signup=$("authToggle").dataset.signup!=="true";$("authToggle").dataset.signup=signup?"true":"false";$("authSubmit").textContent=signup?"Create account":"Sign in";$("authToggle").textContent=signup?"Already have an account? Sign in":"Create an account";$("authMessage").textContent="";$("authPassword").setAttribute("autocomplete",signup?"new-password":"current-password");};$("signOutButton").onclick=async()=>{await supabaseClient.auth.signOut();state.user=null;showAuth(true);setSyncStatus("Signed out");};supabaseClient.auth.getSession().then(async({data})=>{if(data.session){state.user=data.session.user;showAuth(false);try{await loadCloudData();}catch(e){console.error(e);setSyncStatus("Cloud error");alert("Signed in, but cloud data could not be loaded: "+e.message);render();}}else showAuth(true);});}

migrateDefaultExpenseCategories();
$("monthPicker").textContent=new Intl.DateTimeFormat(undefined,{month:"short",year:"numeric"}).format(new Date());
$("date").value=today();
categoryOptions();
render();
setupAuth();

document.querySelectorAll("[data-period]").forEach(b=>b.onclick=()=>{state.period=b.dataset.period;document.querySelectorAll("[data-period]").forEach(x=>x.classList.toggle("active",x===b));render();});
$("addButton").onclick=openNewTransaction;
$("closeDialog").onclick=()=>$("transactionDialog").close();
document.querySelectorAll(".type-choice").forEach(b=>b.onclick=()=>{state.type=b.dataset.type;document.querySelectorAll(".type-choice").forEach(x=>x.classList.toggle("active",x===b));categoryOptions();});
$("manageCategories").onclick=()=>{const panel=$("categoryManager");panel.hidden=!panel.hidden;if(!panel.hidden)$("newCategory").focus();};
$("addCategory").onclick=async()=>{const input=$("newCategory"),name=input.value.trim();if(!name)return input.focus();if(state.categories[state.type].some(c=>c.toLowerCase()===name.toLowerCase()))return alert("That category already exists.");state.categories[state.type].push(name);localPersist();input.value="";categoryOptions();$("category").value=name;if(state.user){try{await saveCategoriesCloud();setSyncStatus("Synced");}catch(e){console.error(e);setSyncStatus("Local only");}}};
$("transactionForm").onsubmit=async event=>{event.preventDefault();const f=new FormData(event.target),entry={id:state.editingId||crypto.randomUUID(),type:state.type,description:f.get("description").trim(),amount:Number(f.get("amount")),category:f.get("category"),date:f.get("date")};if(state.editingId)state.entries=state.entries.map(existing=>existing.id===state.editingId?entry:existing);else state.entries.push(entry);state.editingId=null;localPersist();event.target.reset();$("date").value=today();categoryOptions();$("transactionDialog").close();render();if(state.user){try{await saveEntryCloud(entry);setSyncStatus("Synced");}catch(e){console.error(e);setSyncStatus("Local only");alert("Saved locally, but cloud sync failed: "+e.message);}}};
$("typeFilter").onchange=render;
$("categoryFilter").onchange=render;
$("clearFilters").onclick=()=>{$("typeFilter").value="all";$("categoryFilter").value="all";render();};