const defaultCategories = { expense: ["Grocery Shopping", "Outside Food", "Fashion Shopping", "Utility Bills", "Car Expenses", "Medical Expenses", "Entertainment", "Vacation Expenses", "Others"], income: ["Salary", "Freelance", "Gift", "Investment", "Other"] };
const symbols = { "Grocery Shopping":"🛒", "Outside Food":"🍽", "Fashion Shopping":"🛍", "Utility Bills":"◉", "Car Expenses":"🚗", "Medical Expenses":"✚", Entertainment:"★", "Vacation Expenses":"✈", Others:"•", Salary:"▣", Freelance:"⌘", Gift:"♡", Investment:"↗", Other:"•" };
const $ = (id) => document.getElementById(id);
let state = { period:"month", type:"expense", editingId:null, entries: JSON.parse(localStorage.getItem("monee-entries") || "[]"), categories: JSON.parse(localStorage.getItem("monee-categories") || "null") || JSON.parse(JSON.stringify(defaultCategories)) };
const money = { format: (value) => `⃁ ${Number(value).toLocaleString("en-SA", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` };
const today = () => new Date().toISOString().slice(0,10);
function persist(){ localStorage.setItem("monee-entries",JSON.stringify(state.entries)); localStorage.setItem("monee-categories",JSON.stringify(state.categories)); }
function migrateDefaultExpenseCategories(){
  if(localStorage.getItem("monee-category-migration-v2")) return;
  const mapping = { Food:"Grocery Shopping", Transport:"Car Expenses", Shopping:"Fashion Shopping", Bills:"Utility Bills", Health:"Medical Expenses", Other:"Others" };
  state.entries.forEach(entry=>{ if(entry.type==="expense" && mapping[entry.category]) entry.category=mapping[entry.category]; });
  const oldDefaults = ["Food","Transport","Shopping","Bills","Health","Entertainment","Other"];
  const custom = state.categories.expense.filter(category=>!oldDefaults.includes(category));
  state.categories.expense = [...defaultCategories.expense, ...custom.filter(category=>!defaultCategories.expense.includes(category))];
  localStorage.setItem("monee-category-migration-v2", "true");
  persist();
}
function samePeriod(date){ const d=new Date(date+"T12:00:00"), now=new Date(); if(state.period==="all") return true; if(state.period==="month") return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear(); const start=new Date(now); start.setHours(0,0,0,0); start.setDate(now.getDate()-((now.getDay()+6)%7)); return d>=start; }
function categoryOptions(){ $("category").innerHTML=state.categories[state.type].map(x=>`<option>${escapeHTML(x)}</option>`).join(""); renderCategoryManager(); }
function renderCategoryManager(){ $("editableCategories").innerHTML=state.categories[state.type].map((name,index)=>`<button class="category-chip" type="button" data-category-index="${index}"><span>${escapeHTML(name)}</span><i aria-hidden="true">✎</i></button>`).join(""); document.querySelectorAll("[data-category-index]").forEach(button=>button.onclick=()=>renameCategory(Number(button.dataset.categoryIndex))); }
function renameCategory(index){ const oldName=state.categories[state.type][index], newName=prompt("Rename category",oldName); if(newName===null) return; const name=newName.trim(); if(!name||name===oldName) return; if(state.categories[state.type].some(c=>c.toLowerCase()===name.toLowerCase())) return alert("That category already exists."); state.categories[state.type][index]=name; state.entries.forEach(e=>{if(e.type===state.type&&e.category===oldName)e.category=name;}); persist(); categoryOptions(); refreshFilters(); render(); }
function getEntries(){ const type=$("typeFilter").value, cat=$("categoryFilter").value; return state.entries.filter(e=>samePeriod(e.date)&&(type==="all"||e.type===type)&&(cat==="all"||e.category===cat)); }
function refreshFilters(){ const current=$("categoryFilter").value; const cats=[...new Set(state.entries.filter(e=>e.type==="expense").map(e=>e.category))]; $("categoryFilter").innerHTML='<option value="all">All categories</option>'+cats.map(c=>`<option>${c}</option>`).join(""); $("categoryFilter").value=cats.includes(current)?current:"all"; }
function render(){ refreshFilters(); const entries=getEntries(); const income=entries.filter(e=>e.type==="income").reduce((a,e)=>a+e.amount,0), expense=entries.filter(e=>e.type==="expense").reduce((a,e)=>a+e.amount,0); $("balanceValue").textContent=money.format(income-expense); $("incomeValue").textContent=money.format(income); $("expenseValue").textContent=money.format(expense); $("periodLabel").textContent=state.period==="week"?"Monday–today":state.period==="month"?new Intl.DateTimeFormat(undefined,{month:"long"}).format(new Date()):"Everything"; renderChart(entries); renderCategories(entries); renderTransactions(entries); }
function renderChart(entries){ const expenses=entries.filter(e=>e.type==="expense"); $("chartEmpty").hidden=expenses.length>0; const days=state.period==="week"?7:state.period==="month"?Math.min(new Date().getDate(),7):7; const totals=Array(days).fill(0); expenses.forEach(e=>{const d=new Date(e.date+"T12:00:00"); const pos=state.period==="week"?((d.getDay()+6)%7):d.getDate()%days; totals[pos]+=e.amount}); const max=Math.max(...totals,1); $("chart").innerHTML=totals.map((v,i)=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(4,v/max*100)}%" title="${money.format(v)}"></div><span>${state.period==="week"?["M","T","W","T","F","S","S"][i]:i+1}</span></div>`).join(""); }
function renderCategories(entries){ const grouped={}; entries.filter(e=>e.type==="expense").forEach(e=>grouped[e.category]=(grouped[e.category]||0)+e.amount); const rows=Object.entries(grouped).sort((a,b)=>b[1]-a[1]).slice(0,3); $("categoryList").innerHTML=rows.length?rows.map(([c,v])=>`<div class="category-row"><span class="category-dot">${symbols[c]||"•"}</span><div class="category-info"><b>${c}</b><small>${money.format(v)} spent</small></div><strong class="expense">${money.format(v)}</strong></div>`).join(""):'<p class="empty-message">Your expense categories will appear here.</p>'; }
function renderTransactions(entries){ const sorted=[...entries].sort((a,b)=>b.date.localeCompare(a.date)); $("transactionList").innerHTML=sorted.length?sorted.map(e=>`<div class="transaction"><span class="transaction-icon">${symbols[e.category]||"•"}</span><div class="transaction-info"><b>${escapeHTML(e.description)}</b><small>${e.category} · ${new Date(e.date+"T12:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric"})}</small><div class="entry-actions"><button type="button" class="edit-entry" data-entry-id="${e.id}">Edit</button><button type="button" class="delete-entry" data-entry-id="${e.id}">Delete</button></div></div><strong class="${e.type}">${e.type==="income"?"+":"−"}${money.format(e.amount)}</strong></div>`).join(""):'<p class="empty-message">No transactions for this view.</p>'; document.querySelectorAll(".edit-entry").forEach(button=>button.onclick=()=>editEntry(button.dataset.entryId)); document.querySelectorAll(".delete-entry").forEach(button=>button.onclick=()=>deleteEntry(button.dataset.entryId)); }
function openNewTransaction(){ state.editingId=null; $("transactionForm").reset(); state.type="expense"; $("date").value=today(); document.querySelectorAll(".type-choice").forEach(x=>x.classList.toggle("active",x.dataset.type===state.type)); $("categoryManager").hidden=true; categoryOptions(); $("transactionDialog").showModal(); }
function editEntry(id){ const entry=state.entries.find(e=>e.id===id); if(!entry) return; state.editingId=id; state.type=entry.type; if(!state.categories[entry.type].includes(entry.category)) state.categories[entry.type].push(entry.category); document.querySelectorAll(".type-choice").forEach(x=>x.classList.toggle("active",x.dataset.type===state.type)); categoryOptions(); $("description").value=entry.description; $("amount").value=entry.amount; $("category").value=entry.category; $("date").value=entry.date; $("categoryManager").hidden=true; $("transactionDialog").showModal(); }
function deleteEntry(id){ const entry=state.entries.find(e=>e.id===id); if(!entry || !confirm(`Delete “${entry.description}”?`)) return; state.entries=state.entries.filter(e=>e.id!==id); persist(); render(); }
function escapeHTML(s){const d=document.createElement("div");d.textContent=s;return d.innerHTML;}
$("monthPicker").textContent=new Intl.DateTimeFormat(undefined,{month:"short",year:"numeric"}).format(new Date()); $("date").value=today(); migrateDefaultExpenseCategories(); categoryOptions(); render();
document.querySelectorAll("[data-period]").forEach(b=>b.onclick=()=>{state.period=b.dataset.period;document.querySelectorAll("[data-period]").forEach(x=>x.classList.toggle("active",x===b));render();});
$("addButton").onclick=openNewTransaction; $("closeDialog").onclick=()=>$("transactionDialog").close(); document.querySelectorAll(".type-choice").forEach(b=>b.onclick=()=>{state.type=b.dataset.type;document.querySelectorAll(".type-choice").forEach(x=>x.classList.toggle("active",x===b));categoryOptions();});
$("manageCategories").onclick=()=>{const panel=$("categoryManager"); panel.hidden=!panel.hidden; if(!panel.hidden) $("newCategory").focus();};
$("addCategory").onclick=()=>{const input=$("newCategory"), name=input.value.trim(); if(!name) return input.focus(); if(state.categories[state.type].some(c=>c.toLowerCase()===name.toLowerCase())) return alert("That category already exists."); state.categories[state.type].push(name); persist(); input.value=""; categoryOptions(); $("category").value=name;};
$("transactionForm").onsubmit=(event)=>{event.preventDefault();const f=new FormData(event.target);const entry={id:state.editingId||crypto.randomUUID(),type:state.type,description:f.get("description").trim(),amount:Number(f.get("amount")),category:f.get("category"),date:f.get("date")}; if(state.editingId) state.entries=state.entries.map(existing=>existing.id===state.editingId?entry:existing); else state.entries.push(entry); state.editingId=null; persist();event.target.reset();$("date").value=today();categoryOptions();$("transactionDialog").close();render();};
$("typeFilter").onchange=render; $("categoryFilter").onchange=render; $("clearFilters").onclick=()=>{$("typeFilter").value="all";$("categoryFilter").value="all";render();};
